development:
  adapter: postgresql
  database: foundation_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: foundation_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: foundation_production
  pool: 5
  timeout: 5000